image: google/cloud-sdk:latest

stages:
  - checkout
  - build
  - deploy

variables:
  PROJECT_ID: "encoded-joy-418604"
  REGION: "us-central1"
  REPO_NAME: "my-repo"
  REGISTRY: "us-central1-docker.pkg.dev"
  CLUSTER_NAME: "powerful-kube"

checkout_code:
  stage: checkout
  script:
    - echo "Code checked out successfully"

build_docker_image:
  stage: build
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $GCP_SERVICE_KEY | base64 -d > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - docker build -t $REGISTRY/$PROJECT_ID/$REPO_NAME/mlops-app:latest .
    - docker push $REGISTRY/$PROJECT_ID/$REPO_NAME/mlops-app:latest

deploy_to_gke:
  stage: deploy
  before_script:
    - echo $GCP_SERVICE_KEY | base64 -d > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID
    - kubectl apply -f kubernetes-deployment.yaml

